[package]
name = "rchr"
version = "0.1.0"
authors = ["singaraiona <singaraiona@gmail.com>"]

[[bin]]
name = "rchr"
path = "src/app/rchr.rs"

[dependencies]
itertools = "0.5.9"
lazy_static = "0.2.2"
regex = "0.2"